#page title
page_title                                : 主力狙擊手-台股投資                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1513737933                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             : http://apps.apple.com/app/id1513737933                                             # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=com.newinfo.stockshooter                                          # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : 主力狙擊手-台股投資                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : 籌碼專業分析app

enable_smart_app_banner                   : false                                     # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : StockShooter                               
your_link                                 :                 
your_city                                 :                                 
email_address                             : stockshootertw@gmail.com 
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : 籌碼日報
    description                           : 詳細券商分點統計
    fontawesome_icon_name                 : magic
    
  - title                                 : 三大法人
    description                           : 圖表連動三大法人數據
    fontawesome_icon_name                 : mobile

  - title                                 : 籌碼力道
    description                           : 每日top15買賣力道強弱
    fontawesome_icon_name                 : play-circle

  - title                                 : 八大官股
    description                           : 政府基金買賣力道
    fontawesome_icon_name                 : sync

  - title                                 : 融資、融券
    description                           : 散戶多空力道
    fontawesome_icon_name                 : adjust
  
  - title                                 : 法人借券
    description                           : 法人看空力道
    fontawesome_icon_name                 : star

  - title                                 : 券商連續
    description                           : 連續買賣券商
    fontawesome_icon_name                 : arrow-alt-circle-down

  - title                                 : 券商分點
    description                           : 詳細券商歷史進出資訊
    fontawesome_icon_name                 : link

  - title                                 : 大盤籌碼 (三大法人、融資券、期權)
    description                           : 每日大盤籌碼
    fontawesome_icon_name                 : info-circle

  - title                                 : 選股模組
    description                           : 三大法人買賣超排行榜
    fontawesome_icon_name                 : Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown